# Generated by Django 6.0.5 on 2026-06-01 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectassignment'),
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('task_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='projects.project')),
                ('timesheet_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_details', to='timesheets.timesheetmaster')),
            ],
        ),
    ]
