# Generated by Django 6.0.5 on 2026-06-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_timesheetdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetmaster',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timesheetmaster',
            name='sent_to_client_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetmaster',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SENT_TO_CLIENT', 'Sent To Client')], default='PENDING', max_length=20),
        ),
    ]
