# Generated by Django 6.0.5 on 2026-06-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_timesheetmaster_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetmaster',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
