# Generated by Django 6.0.5 on 2026-06-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_alter_timesheetmaster_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetmaster',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='timesheetmaster',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='timesheetmaster',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='timesheetmaster',
            name='sent_to_client_at',
        ),
        migrations.RemoveField(
            model_name='timesheetmaster',
            name='status',
        ),
    ]
